const GAMES = [
  { name: "Chess",                   micro: 1,  meso: 4,  macro: 10 },
  { name: "Poker",                   micro: 0,  meso: 9,  macro: 7  },
  { name: "Counter-Strike / VALORANT", micro: 9, meso: 7, macro: 6  },
  { name: "League of Legends",       micro: 7,  meso: 6,  macro: 9  },
  { name: "Dota 2",                  micro: 6,  meso: 6,  macro: 10 },
  { name: "Street Fighter",          micro: 9,  meso: 7,  macro: 4  },
  { name: "Tekken",                  micro: 9,  meso: 7,  macro: 3  },
  { name: "Mortal Kombat",           micro: 8,  meso: 6,  macro: 3  },
  { name: "StarCraft II",            micro: 8,  meso: 5,  macro: 10 },
  { name: "Tetris",                  micro: 9,  meso: 0,  macro: 5  },
  { name: "Hearthstone",             micro: 1,  meso: 5,  macro: 8  },
  { name: "Magic: The Gathering",    micro: 2,  meso: 6,  macro: 9  },
  { name: "Among Us",                micro: 0,  meso: 10, macro: 2  },
  { name: "Fortnite",                micro: 8,  meso: 5,  macro: 7  },
  { name: "Warzone / PUBG",          micro: 7,  meso: 7,  macro: 7  },
  { name: "Apex Legends",            micro: 8,  meso: 6,  macro: 6  },
  { name: "Overwatch 2",             micro: 7,  meso: 7,  macro: 7  },
  { name: "Rocket League",           micro: 10, meso: 5,  macro: 5  },
  { name: "Minecraft",               micro: 4,  meso: 2,  macro: 7  },
  { name: "Civilization VI",         micro: 0,  meso: 3,  macro: 10 },
  { name: "Age of Empires II",       micro: 7,  meso: 4,  macro: 9  },
  { name: "Escape from Tarkov",      micro: 8,  meso: 7,  macro: 6  },
  { name: "FIFA / EA FC",            micro: 8,  meso: 6,  macro: 5  },
  { name: "Speedrunning",            micro: 8,  meso: 0,  macro: 10 },
  { name: "Diplomacy",               micro: 0,  meso: 10, macro: 9  },
  { name: "Dungeons & Dragons",      micro: 0,  meso: 9,  macro: 8  },
  { name: "Super Smash Bros.",       micro: 9,  meso: 7,  macro: 4  },
  { name: "Dance Dance Revolution",  micro: 10, meso: 0,  macro: 1  },
  { name: "osu!",                    micro: 10, meso: 0,  macro: 2  },
  { name: "Teamfight Tactics",       micro: 2,  meso: 5,  macro: 9  },
  { name: "XCOM 2",                  micro: 3,  meso: 2,  macro: 9  },
  { name: "Rust",                    micro: 6,  meso: 8,  macro: 7  },
  { name: "Siege (Rainbow Six)",     micro: 8,  meso: 8,  macro: 7  },
  { name: "Halo (multiplayer)",      micro: 8,  meso: 6,  macro: 5  },
  { name: "Splatoon",                micro: 7,  meso: 5,  macro: 6  },
  { name: "Go (board game)",         micro: 1,  meso: 5,  macro: 10 },
  { name: "Backgammon",              micro: 2,  meso: 4,  macro: 8  },
  { name: "Scrabble",                micro: 3,  meso: 4,  macro: 8  },
  { name: "Warcraft III",            micro: 8,  meso: 5,  macro: 9  },
  { name: "Path of Exile",           micro: 5,  meso: 2,  macro: 9  },
];
